language: rust
sudo: required
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
before_deploy:
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: HAwQJ/mtNCQIANEl+ZkD9HTT6jW+aNCSh3p+1Rspq6Q3/ME0SGW/ROj/CEa9Aogt3eGQFeg6p4KMcQhfOvd/ez9vWLRGzv7oZ8p7eGGA6GX9ASrQ0bM19ijQzTUC97uQ/dcjIxBSa86egpPq/pTGnpTYD8VkLLiLbKzmIauboQT6Q4aVOY4tpOIsv6lBY8qZICxjiU0tf+KnRZ9gpknhlXLz6Q7fKQYG46om+l7p+HRNK2DagiwZzTIE2AfoZhUEW8qOtXF0k5CB5rIBStDRIxcR58j7ODKEvmfi9JEJFKYLB5BmmhFbEPDltCrRAXAfAak8nDaeee2EHd7PRzl29taff5tqvgghC1sttrIF7cCV8vj3qjVNe66IS1FIroE7Q1pW0uuK726kcYXzeaaxPqhuka/i4xQR4r4EH9h9lF4pSyGy5OYJY2wppPG1KFRwXs3JMeIoF4mOQYcgNRKJWZgsdvC50TlcinKz1lx34KnvFz0EYHEVEO8OxgSD/1czxt8+/+oLdKM3/rjbj/at79I7W+F7GwphjGoPoeQqo4SCLqFnKxyDQxctCkgsEdOXRbfV7b2NJo6rM6EDRn7uNQp/oipSMMgp5nMo7XYKX469scbgvotpVMHW1NdHa39xVso3RfJse0yKzisowv/DhFIX6VqMqVaNPUPe2EeG0f8=
  file: "./target/debug/K-means"
  on:
    repo: entscheidungsproblem/K-means
