language: rust
sudo: required
cache: cargo
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
before_script:
- |
  if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
    export NIGHTLY=true
  fi
- "if [[ $NIGHTLY ]]; then \n  rustup component add rustfmt-preview;\nfi  \n"
- export PATH=$PATH:~/.cargo/bin
script:
- |
  if [[ $NIGHTLY ]]; then
    cargo fmt --all -- --check;
  fi
- cargo build --verbose;


before_deploy:
- pwd;
- ls -la target;
- ls -la target/debug;
- git status;
- git branch;

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: NblCrbgWorneNVXcsSovShTi0srjfnKA80x9nI3NWBBz9R1U4yr4r9OiDPBjJURNmVzfBvnav+gn1ugHULoLg36L58sV8Rj8E+QskN5KTeB7itEFvQBJHwRiN9riP/+wFKaaezIR26XqI6hQPAz4pDqf/QP94DNVWgIO9EEGKLzDgMQt++3s7kaIV99dws0y7LYmbdDiBNhrPBN9MQy3aTymtYADZNRz/XXk+NoY18YByoDQaXB4BDwIdHVqoynX32p/h1yyL8QVj+TbjuskcTZUrj82J8aEZ/DlSux7qiPy1/TYFRQ/sx/MxLF25e6B26fXMvmWksJFGxTCt9BhPHETS2+kKNXomFCNKaC3oY1b9b/xmHJVHjuAQRk9KCw5kznGb4QULTA4I3nUojbvZqlQIYAZnS+h+b/E6FwGKG3rLwZEWQuPl9I2OIP+bMwWsSdKwip1mvkydO8SZN+CLp3g+NgR5dCQ99sw/sHLrq76ZDJ8y8jWN/cSio51W9vSmP6uhVbITjYP78/LBaAKIY1CN46DTuXNMV6AQeJChs6YKTCk2qxK9C2kbReE2Lg5ga0OaZrhBaLECPz5XZju7q2TE97kR9yUu093u769C4YmqX1EMAilPgOkkZQUF7sEi/YKMp2bR7EwBbqBWUiHp1MyfmuSgPDibMeY3ykSJNY=
  file: 
    - "TODO.txt"
    - "target/debug/K-means"
  on:
    repo: entscheidungsproblem/K-means
    branch: $TRAVIS_TAG
    condition: $TRAVIS_RUST_VERSION = stable && $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
