language: rust
sudo: required
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  
before_script:
  - |
      if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
        export NIGHTLY=true
      fi
  - |
      if [[ $NIGHTLY ]]; then 
        rustup component add rustfmt-preview;
      fi  
  - export PATH=$PATH:~/.cargo/bin
  
script:
  - |
      if [[ $NIGHTLY ]]; then
        cargo fmt --all -- --check;
      fi
      
before_deploy:
  - pwd;
  - ls -la;

deploy:
  provider: releases
  api_key:
    secure: "hXhtxCkciLLsfb8CvgyGzzrKAvWTrXYu1GwHSIHG4aAsn+k87vW63MSC79o7lMo6Ri69OMpKscP92jxkBAUwunjh7w8mh0/1NEzGNSyp3W3WaKCrJx6XnzEQTbnI3TJWzbL+y67uqAmYnsY9pGN7Gwd3EIdfmD5RCIhsUIHs7aXzIab/Y5SVX0tlhYyrX5MTGCjd0wWgQw83C23dprcJnPTqSVvHS8NL02iq2KV1bMsdfK5nXL049ZThFsIzllp6Iy9PBf+yXNVmtrnEIb+M6usmz97U6WGZBk5a3tCyOq+kewp+KWWylWzaR+/ZwsY1s7K79Hj51lCG72t6meA9RU01pzJU7wUqQ+PBKpDR/8fYzXCqjUhijFSja7tFeKk0nmZut527TWh0yzm58mh2g7Lvieyk9xRgST7nbP5EVuMISpAvpJ8loFBK9MI4LPv1g4sL1yOkoICzyvEVyDE8kevD1Ub8vFvE2F2PEaQGAEMv8RW+ZcyVXjEaGMBDP7wP/2uTWw9MxgazhTY+8r5CPUR0lYpup9YKSvgvfH0XrF4Zgw0sDQu69tBJq8FbRnuKNaXn+NO8N2FvL3jux899ECBRJ3UUvjIaDOpn4AYst29l6WK7gDbNRduELc8r/6qJTeooAYdJWCvjMAhvA9JNz2XKteFvK8O4vRxSq/FREBA="
  file_glob: true
  file: "target/debug/deps/K_means-*"
  on:
    repo: entscheidungsproblem/K-means
    tags: true
    branches: master
    condition: $TRAVIS_RUST_VERSION = stable
