language: rust
sudo: required
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
  
before_deploy:
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: Ans3BhoZhnVVuHS/WszAs/OMtbpvqmOo1YXekRltxtcmUgw8GPS4klbFHB2GyghPv+oeLp0j9WSzqRifoxZuuD+Nw/FN4a9FyK8OaTIJlNk8obklClpdHq4V7CO0ZAkN5fWZhlb3dJ+rn6KYQQe82JLwkvw5bjP4i3G2jsKqYebwpBhBhkQ4HVC/g0G1B77Nyi3+Dz+sqsCej7Z/wTakcsw1aKeT/I1gxDna38CA6czKLIU4zVlvuvNpZWUWI65vi2mIV3Cc87tcHc99mt91tbnmQ2S1iXGLcnu23avxuW90k81ACKPw2Js/Z28qXKySsiunwNzF8XaKSt1TbPIsbACBZ8ModVOBzHzLN1teeZVbBMmn/sdO5tyvezywEhWoxCslG1V87d/sT3UntGJk7cfInm0t6ESr++j0c/Cjac5IjOscfYvUEoX137947mr8Npqn78/M3ZpSrGH/7aYGDpTNTUtgqv6xmqPvP5bvbNckEZqQhH9fVHCRmI/suV0iX58ixB15YST21cWa6N31MTZqYRhGtijZVhXkv6GAmhLk5N0NzV2iY1oZ56rV2tKeeFMnOV7XwGt8srToFKiaHF+t6DIj1Gie2Rk4lrhelhVVmRTsDJPQw7/Vvl3+1h5biO4cWbe4d+zBCdEGQKJpt56iNo+KJZaQeDdI316Y030=
  file: target/debug/K-means
  on:
    condition: $TRAVIS_RUST_VERSION = stable
